"""Added tables

Revision ID: 02b400c8e03f
Revises: db4a97bb3957
Create Date: 2023-04-07 19:49:48.556929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02b400c8e03f'
down_revision = 'db4a97bb3957'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
