"""Added tables

Revision ID: 246096c86de0
Revises: 2fd449943edf
Create Date: 2023-04-07 19:56:03.600369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '246096c86de0'
down_revision = '2fd449943edf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
