"""Added tables

Revision ID: 2fd449943edf
Revises: bf5ee7364f0b
Create Date: 2023-04-07 19:54:11.025852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fd449943edf'
down_revision = 'bf5ee7364f0b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
