"""Added tables

Revision ID: 60d6dd4b0022
Revises: c0559a70053d
Create Date: 2023-04-07 19:36:43.187847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60d6dd4b0022'
down_revision = 'c0559a70053d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
