"""Added tables

Revision ID: a9ce8ab6313a
Revises: 246096c86de0
Create Date: 2023-04-07 19:56:41.127791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9ce8ab6313a'
down_revision = '246096c86de0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
