"""Added tables

Revision ID: bf5ee7364f0b
Revises: 02b400c8e03f
Create Date: 2023-04-07 19:52:47.948749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf5ee7364f0b'
down_revision = '02b400c8e03f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
