"""Added tables

Revision ID: c6101b559ce6
Revises: a9ce8ab6313a
Create Date: 2023-04-07 19:57:06.968120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6101b559ce6'
down_revision = 'a9ce8ab6313a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('note', sa.Column('new_idea', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('note', 'new_idea')
    # ### end Alembic commands ###
