"""Added tables

Revision ID: db4a97bb3957
Revises: 60d6dd4b0022
Create Date: 2023-04-07 19:48:56.786697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db4a97bb3957'
down_revision = '60d6dd4b0022'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
