"""removed idea

Revision ID: ec9468438788
Revises: c6101b559ce6
Create Date: 2023-04-07 19:58:22.365763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec9468438788'
down_revision = 'c6101b559ce6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('note', 'new_idea')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('note', sa.Column('new_idea', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
